### ISSUE TITLE
table2lol: ul instead of ol

### ISSUE THREAD

**Issue by mustafa0x** [bpj/pandoc-list-table#2]
Very useful filter, thank you. Alleviates the pain of markdown's finicky table syntax.

Is there a way to have table2lol output something like

```
*   -   foo
    -   bar
    -   baz
```

**Comment by bpj** [comment]
Not currently, because I have found that it is much easier to keep track of which cell a list item corresponds to with ordered lists.

How does this inconvenience you? Note that the list markers in an ordered list need not be in correct sequence. You can use `0.` or even `#.` everywhere when you change/add lists. It doesn't affect the resulting table in any way. If you want to use the list as a list in your output you can use a filter to convert ordered lists (in a certain div) to bullet lists. Just run that filter after this filter.

**Comment by mustafa0x** [comment]
Ah, ok. Just for consistency with the hand-written lists of lists tables I wrote.

I wrote a few regexes as a workaround for now.
