### ISSUE TITLE
Don't add cells the user didn't add

### ISSUE THREAD

**Issue by mustafa0x** [bpj/pandoc-list-table#3]
```
$> pandoc --lua-filter pandoc-list-table.lua

::: lol2table
*   - a
    - b
*   - c
:::
```

```html
<table>
  <caption></caption>
  <thead>
    <tr class="header">
      <th>a</th>
      <th>b</th>
    </tr>
  </thead>
  <tbody>
    <tr class="odd">
      <td>c</td>
      <td></td> <!-- <<< added-->
    </tr>
  </tbody>
</table>
```

Is there a way to tell pandoc-list-table to not add a cell next to c?

Thank you!

Updated: I looked at the codebase and found the code below. Maybe I could try just removing it?

```moon
    -- Make sure all rows are the same length by adding empty
    -- cells until they are the same length as the longest row
    for row in *rows
      while #row < col_count
        row[#row+1] = {}
```

**Comment by bpj** [comment]
The SimpleTable model, and LaTeX, requires that all rows have a cell for every column, otherwise I wouldn't have added that code. It is possible that it would work with the complex table model and HTML but that model is very hairy and I don't currently have the time to modify the filter to use it. Pull requests are welcome though! :-)

**Comment by mustafa0x** [comment]
Thanks, really appreciate the reply! I had a feeling there was a good reason for that. :)

As a crude workaround I set the text of added cells to `ADDED_FIELD` so I can later remove them (even this simple solution took quite a while, being a Lua and pandoc API newbie).

Thanks.
