### ISSUE TITLE
Preserve attributes

### ISSUE THREAD

**Issue by not-my-profile** [bpj/pandoc-list-table#4]
```
::: {.lol2table #some-id .some-class lang=en}

A table of stuff.

-   -   foo
    -   bar
    -   baz
-   -   -   tic
        -   pic
    -   -   tac
        -   pac
    -   -   toc
        -   poc
:::
```

currently produces `<table>...</table>`. I would expect it to produce:
```
<table id="some-id" class="some-class" lang="en">...</table>
```

(sometimes you want/need to add attributes directly to the table as opposed to a wrapping div)

**Comment by not-my-profile** [comment]
Closing this, since I no longer need it. (I have since implemented [my own lua filter](https://github.com/pandoc/lua-filters/tree/master/list-table)).

**Comment by bpj** [comment]
As you probably have discovered the formatting of HTML tables is done by Pandoc. This filter just creates a Pandoc table object which it returns to Pandoc.

**Comment by not-my-profile** [comment]
Yeah ... I meant that the attributes set on the div could be passed onto the generated table.

**Comment by bpj** [comment]
They can't because Pandoc table objects don't take attributes. The attributes on arbitrary elements in Common Mark are translated into divs and spans in the AST.

**Comment by not-my-profile** [comment]
[Pandoc tables do take attributes](https://pandoc.org/lua-filters.html#type-table).

**Comment by bpj** [comment]
OK I didn't know that but I wouldn't touch the Table as opposed to
SimpleTable object. It's insanely complex for little benefit. What people
wanted was colspan and rowspan. That could have been implemented without
such a freak object. Moreover an LoL is a perfect fit for a SimpleTable.
CSS is no problem since you can always use a child selector.

Den tors 23 dec. 2021 21:18Martin Fischer ***@***.***> skrev:
